### ISSUE TITLE
current_memory token not working

### ISSUE THREAD

**Issue by axic** [wanderer/wast-graph#2]
```
(module
  (func
    (current_memory)
  )
)
```

breaks `wast-graph`:

```
/Users/alex/Projects/ewasm/cleanup-ewasm/node_modules/wast-graph/index.js:61
      branches.forEach(function (br) {
              ^

TypeError: Cannot read property 'forEach' of undefined
    at AST.parse (/Users/alex/Projects/ewasm/cleanup-ewasm/node_modules/wast-graph/index.js:61:15)
    at new AST (/Users/alex/Projects/ewasm/cleanup-ewasm/node_modules/wast-graph/index.js:16:10)
    at AST.set (/Users/alex/Projects/ewasm/cleanup-ewasm/node_modules/generic-digraph/index.js:135:16)
    at /Users/alex/Projects/ewasm/cleanup-ewasm/node_modules/wast-graph/index.js:64:16
    at Array.forEach (native)
    at AST.parse (/Users/alex/Projects/ewasm/cleanup-ewasm/node_modules/wast-graph/index.js:61:16)
    at new AST (/Users/alex/Projects/ewasm/cleanup-ewasm/node_modules/wast-graph/index.js:16:10)
    at AST.set (/Users/alex/Projects/ewasm/cleanup-ewasm/node_modules/generic-digraph/index.js:135:16)
    at json.forEach (/Users/alex/Projects/ewasm/cleanup-ewasm/node_modules/wast-graph/index.js:54:16)
    at Array.forEach (native)
```

**Comment by wanderer** [comment]
ok it should be fixed here https://github.com/wanderer/wast-graph/commit/ac6c815db92bbecea15d1b1df7df5f3049973d03 I addded a simple test that searches for the node here https://github.com/wanderer/wast-graph/blob/master/test/index.js#L310

**Comment by axic** [comment]
works, thanks!
